# Generated by Django 4.2.2 on 2023-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_acerca_articulo_etiqueta_perfil_red_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='bajada',
            field=models.CharField(max_length=600, verbose_name='Bajada'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/articulos/imagenes', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
